### ISSUE TITLE
pip crashed after installation of requests_ntlm

### ISSUE THREAD

**Issue by pshen** [requests/requests-ntlm#101]
Hi all,

in a fresh Ubuntu 16.04 LTS instance, after installation of requests_ntlm package via pip, pip crashed just right after.

Installation.

```
root@test-vm:/usr/lib/python2.7/dist-packages# pip install requests_ntlm
Collecting requests_ntlm
  Downloading requests_ntlm-1.1.0-py2.py3-none-any.whl
Collecting ntlm-auth>=1.0.2 (from requests_ntlm)
  Downloading ntlm_auth-1.0.6-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0.0 in /usr/lib/python2.7/dist-packages (from requests_ntlm)
Collecting cryptography>=1.3 (from requests_ntlm)
  Downloading cryptography-2.1.3-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 481kB/s 
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from ntlm-auth>=1.0.2->requests_ntlm)
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.3->requests_ntlm)
  Downloading cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl (405kB)
    100% |████████████████████████████████| 409kB 2.7MB/s 
Requirement already satisfied (use --upgrade to upgrade): enum34; python_version < "3" in /usr/lib/python2.7/dist-packages (from cryptography>=1.3->requests_ntlm)
Collecting idna>=2.1 (from cryptography>=1.3->requests_ntlm)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 8.5MB/s 
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3->requests_ntlm)
  Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 8.8MB/s 
Requirement already satisfied (use --upgrade to upgrade): ipaddress; python_version < "3" in /usr/lib/python2.7/dist-packages (from cryptography>=1.3->requests_ntlm)
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3->requests_ntlm)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 4.0MB/s 
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /root/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built pycparser
Installing collected packages: ntlm-auth, pycparser, cffi, idna, asn1crypto, cryptography, requests-ntlm
  Found existing installation: idna 2.0
    Not uninstalling idna at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: cryptography 1.2.3
    Not uninstalling cryptography at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed asn1crypto-0.23.0 cffi-1.11.2 cryptography-2.1.3 idna-2.6 ntlm-auth-1.0.6 pycparser-2.18 requests-ntlm-1.1.0
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Right after installation.
```
root@test-vm:/usr/lib/python2.7/dist-packages# pip list
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 13, in <module>
    from pip.exceptions import InstallationError, CommandError, PipError
  File "/usr/lib/python2.7/dist-packages/pip/exceptions.py", line 6, in <module>
    from pip._vendor.six import iteritems
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 3, in <module>
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/__init__.py", line 53, in <module>
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 54, in <module>
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

**Comment by pshen** [comment]
I found a workaround.

Before install requests_ntlm, the pip version from Ubuntu is 8.1.1.

If I run a "pip install --upgrade pip", and then install requests_ntlm package, the pip will not crash.

**Comment by jborean93** [comment]
That isn't a workaround but what you should be doing in this case. Over time newer features are added to the pypi and the packaging process that requires both pip and setuptools to be on a newer release.
