### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by LiaungYip** [requests/requests-ntlm#54]
Attempting to import requests_ntlm on Python 2.7.9 raises a TypeError. This renders the module unusable.

See also this StackOverflow question about a very similar error: http://stackoverflow.com/questions/27660034/python-requests-ntlm-import-error . (The user in that post got a `'long' object is not subscriptable` error. I had also experienced that error before updating Python to latest.)

```
PS C:\Users\lws> python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests_ntlm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\requests_ntlm\__init__.py", line 1, in <module>
    from .requests_ntlm import HttpNtlmAuth
  File "C:\Python27\lib\site-packages\requests_ntlm\requests_ntlm.py", line 4, in <module>
    from ntlm3 import ntlm
  File "C:\Python27\lib\site-packages\ntlm3\__init__.py", line 2, in <module>
    from . import HTTPNtlmAuthHandler  # noqa
  File "C:\Python27\lib\site-packages\ntlm3\HTTPNtlmAuthHandler.py", line 20, in <module>
    from . import ntlm
  File "C:\Python27\lib\site-packages\ntlm3\ntlm.py", line 25, in <module>
    from . import des
  File "C:\Python27\lib\site-packages\ntlm3\des.py", line 19, in <module>
    from . import des_c
  File "C:\Python27\lib\site-packages\ntlm3\des_c.py", line 19, in <module>
    from .des_data import des_SPtrans, des_skb
  File "C:\Python27\lib\site-packages\ntlm3\des_data.py", line 25, in <module>
    U32(0x00820200), U32(0x00020000), U32(0x80800000), U32(0x80820200),
  File "C:\Python27\lib\site-packages\ntlm3\U32.py", line 32, in __init__
    value = six.byte2int(value)
  File "C:\Python27\lib\site-packages\six.py", line 625, in byte2int
    return ord(bs[0])
TypeError: 'long' object has no attribute '__getitem__'
>>>
```

Package versions in use:
```
PS C:\Users\lws> pip show requests-ntlm requests python-ntlm3 six
---
Name: requests-ntlm
Version: 0.1.0
Location: c:\python27\lib\site-packages
Requires: requests, python-ntlm3
---
Name: requests
Version: 2.5.1
Location: c:\python27\lib\site-packages
Requires:
---
Name: python-ntlm3
Version: 1.0.1
Location: c:\python27\lib\site-packages
Requires: six
---
Name: six
Version: 1.9.0
Location: c:\python27\lib\site-packages
Requires:
```

**Comment by Lukasa** [comment]
Interesting. I bet this didn't happen on 2.7.8, and this problem is well down in the depths of python-ntlm3. You're reporting the bug on the wrong library, I'm afraid: consider reporting on [trustrachel/python-ntlm3](https://github.com/trustrachel/python-ntlm3).

**Comment by trustrachel** [comment]
Huh, I wonder if there's something oddball about Windows - the SO problem was on Windows, too. 

Just importing the library causes the problem? I'll try to find a windows box to reproduce this on.

**Comment by trustrachel** [comment]
Sorry @Lukasa didn't see you closed it. Yes, please, send me a bug and I'll take a look.

**Comment by Lukasa** [comment]
Oh hey @trustrachel, I didn't know you were watching this repo! Would you rather have this issue open here? I don't mind tracking it here, just didn't know you were watching.

**Comment by trustrachel** [comment]
I just happened to see it when I was looking for something else. I think you're right, it's my library. Better it be over there. :)

**Comment by Lukasa** [comment]
Cool, alrighty then. =) Thanks for being so responsive!

**Comment by LiaungYip** [comment]
A further note; requests_ntlm version 0.0.3 imports OK. All other dependency versions are unchanged.

```
PS C:\Users\lws> pip install requests-ntlm==0.0.3
Downloading/unpacking requests-ntlm==0.0.3
  Downloading requests_ntlm-0.0.3.tar.gz
  Running setup.py (path:c:\users\lws\appdata\local\temp\pip_build_lws\requests-ntlm\setup.py) egg_info for package requests-ntlm

Requirement already satisfied (use --upgrade to upgrade): requests>=1.0.0 in c:\python27\lib\site-packages (from requests-ntlm==0.0.3)
Requirement already satisfied (use --upgrade to upgrade): python-ntlm in c:\python27\lib\site-packages (from requests-ntlm==0.0.3)
Installing collected packages: requests-ntlm
  Running setup.py install for requests-ntlm

Successfully installed requests-ntlm
Cleaning up...
PS C:\Users\lws> python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests_ntlm
>>>
```
