### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Zitrax** [requests/requests-ntlm#62]
I am using 0.2.0 and I am getting this:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 579, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "C:\Python27\lib\site-packages\requests\hooks.py", line 41, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "C:\Python27\lib\site-packages\requests_ntlm\requests_ntlm.py", line 119, in response_hook
    'Authorization', r, kwargs)
  File "C:\Python27\lib\site-packages\requests_ntlm\requests_ntlm.py", line 91, in retry_using_http_NTLM_auth
    ))[0].strip()
IndexError: list index out of range
```

And inspecting `auth_header_value` I can see it starts with "Negotiate, NTLM " and the code is splitting on ',' and then using `startswith('NTLM '). But after the split the value starts with ' NTLM '.

I verified that it works on my side is I split on ', ' instead, but that's not the proper fix ofc.

**Comment by Lukasa** [comment]
I think the better fix is to lstrip whitespace. A pull request is welcome. =)
