### ISSUE TITLE
Traceback occurred

### ISSUE THREAD

**Issue by densminger** [requests/requests-ntlm#90]
Trying to authenticate to Sharepoint via NTLM, and I'm getting the following Traceback:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/requests-2.2.0-py2.7.egg/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.2.0-py2.7.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.2.0-py2.7.egg/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.2.0-py2.7.egg/requests/sessions.py", line 491, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.2.0-py2.7.egg/requests/hooks.py", line 41, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/Library/Python/2.7/site-packages/requests_ntlm/requests_ntlm.py", line 146, in response_hook
    kwargs
  File "/Library/Python/2.7/site-packages/requests_ntlm/requests_ntlm.py", line 47, in retry_using_http_NTLM_auth
    server_certificate_hash = _get_server_cert(response)
  File "/Library/Python/2.7/site-packages/requests_ntlm/requests_ntlm.py", line 205, in _get_server_cert
    socket = raw_response._fp.fp._sock
AttributeError: 'NoneType' object has no attribute '_sock'

**Comment by Lukasa** [comment]
Huh, Requests 2.2 is quite old. I wouldn't be at all surprised to find that that has busted our assumption about where things are. Can you try upgrading your requests?

**Comment by densminger** [comment]
I upgraded to requests-2.13 and that fixed the issue.

**Comment by Lukasa** [comment]
Cool. We should probably work out what the actual required Python version is and update our `setup.py` accordingly.

**Comment by rjsquire** [comment]
Has anyone seen this issue lately?  

I have the following packages installed:
```
requests                           2.19.1
requests-ntlm                      1.1.0
ntlm-auth                          1.2.0
```
`Python 2.7.14`

The code that actually throws the exception:
```
def request_future_price(event):
    if event.get('account_type', '') == 'epnet':
        epnet_id = event.get('account_id',{}).get('epnet_id','')
        account_uri = '{}{}'.format(EPNET_API_HOST, epnet_id)
        print ('Requesting future price from {}'.format(account_uri))
        # import pdb; pdb.set_trace()
        # future_price_request = requests.get(account_uri,
        #     auth=HTTPBasicAuth('rsquire', 'ButterM1lk'))
        session = requests.Session()
        session.auth = HttpNtlmAuth('DOMAIN\\myusername','myPassWord')
        future_price_request = session.get(account_uri)
        print(future_price_request)
        
    elif event.get('account_type', '') == 'sap':
        raise "SAP accounts are not yet supported"
```

The output that I'm seeing is:
```
 handle(event, context)
     27     acount_type = event.get('account_type', '')
     28     account_id = event.get('account_id', {})
---> 29     correspondene_request = get_correspondence_request(event)
     30     # type specific vars
     31

/Users/rsquire/dev/portal/lambdas/functions/request_future_price/request_future_price.py in get_correspondence_request(event)
     54     cr = event
     55     # try:
---> 56     future_price = request_future_price(event)
     57     # except Exception as e:
     58     #     # the failure details go here.

/Users/rsquire/dev/portal/lambdas/functions/request_future_price/request_future_price.py in request_future_price(event)
     45         session = requests.Session()
     46         session.auth = HttpNtlmAuth('DOMAIN\\myusername','myPassWord')
---> 47         future_price_request = session.get(account_uri)
     48         print(future_price_request)
     49

/Users/rsquire/dev/portal/lambdas/functions/request_future_price/requests/sessions.pyc in get(self, url, **kwargs)
    393
    394         kwargs.setdefault('allow_redirects', True)
--> 395         return self.request('GET', url, **kwargs)
    396
    397     def options(self, url, **kwargs):

/Users/rsquire/dev/portal/lambdas/functions/request_future_price/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert)
    381             'allow_redirects': allow_redirects,
    382         }
--> 383         resp = self.send(prep, **send_kwargs)
    384
    385         return resp

/Users/rsquire/dev/portal/lambdas/functions/request_future_price/requests/sessions.pyc in send(self, request, **kwargs)
    489
    490         # Response manipulation hooks
--> 491         r = dispatch_hook('response', hooks, r, **kwargs)
    492
    493         # Persist cookies

/Users/rsquire/dev/portal/lambdas/functions/request_future_price/requests/hooks.pyc in dispatch_hook(key, hooks, hook_data, **kwargs)
     39
     40         for hook in hooks:
---> 41             _hook_data = hook(hook_data, **kwargs)
     42             if _hook_data is not None:
     43                 hook_data = _hook_data

/Users/rsquire/.pyenv/versions/2.7.14/envs/future-price/lib/python2.7/site-packages/requests_ntlm/requests_ntlm.pyc in response_hook(self, r, **kwargs)
    149                     r,
    150                     auth_type,
--> 151                     kwargs
    152                 )
    153         elif r.status_code == 407:

/Users/rsquire/.pyenv/versions/2.7.14/envs/future-price/lib/python2.7/site-packages/requests_ntlm/requests_ntlm.pyc in retry_using_http_NTLM_auth(self, auth_header_field, auth_header, response, auth_type, args)
     50                                    response, auth_type, args):
     51         # Get the certificate of the server if using HTTPS for CBT
---> 52         server_certificate_hash = self._get_server_cert(response)
     53
     54         """Attempt to authenticate using HTTP NTLM challenge/response."""

/Users/rsquire/.pyenv/versions/2.7.14/envs/future-price/lib/python2.7/site-packages/requests_ntlm/requests_ntlm.pyc in _get_server_cert(self, response)
    187                     socket = raw_response._fp.fp.raw._sock
    188                 else:
--> 189                     socket = raw_response._fp.fp._sock
    190
    191                 try:

AttributeError: 'NoneType' object has no attribute '_sock'
