### ISSUE TITLE
error on python 3.6 - TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by mphuie** [requests/requests-ntlm#96]

**Comment by mphuie** [comment]
`   if re.match(r'^[a-fA-F\d]{32}:[a-fA-F\d]{32}$', password):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object`

**Comment by Lukasa** [comment]
Can you provide the *full* traceback please?

**Comment by mphuie** [comment]
Full trace

`Traceback (most recent call last):
  File "<project-path>/env/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "<project-path>/env/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "<project-path>/env/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<project-path>/env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "<project-path>/env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "<project-path>/env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "<project-path>/env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "<project-path>/env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "<project-path>env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "<project-path>env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<project-path>env/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "<project-path>env/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 42, in wrapper
    response = function(request)
  File "<project-path>env/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 195, in wrapper
    return function(**kwargs)
  File "<project-path>/api.py", line 35, in teams
    resp = sess.get(get_teams, verify=False)
  File "<project-path>/env/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "<project-path>/env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "<project-path>/env/lib/python3.6/site-packages/requests/sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "<project-path>/env/lib/python3.6/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "<project-path>/env/lib/python3.6/site-packages/requests_ntlm/requests_ntlm.py", line 146, in response_hook
    kwargs
  File "<project-path>/env/lib/python3.6/site-packages/requests_ntlm/requests_ntlm.py", line 116, in retry_using_http_NTLM_auth
    server_certificate_hash=server_certificate_hash
  File "<project-path>/env/lib/python3.6/site-packages/ntlm_auth/ntlm.py", line 125, in create_authenticate_message
    server_certificate_hash)
  File "<project-path>/env/lib/python3.6/site-packages/ntlm_auth/messages.py", line 243, in __init__
    self.lm_challenge_response = compute_response.get_lm_challenge_response()
  File "<project-path>/env/lib/python3.6/site-packages/ntlm_auth/compute_response.py", line 83, in get_lm_challenge_response
    self._client_challenge)
  File "<project-path>/env/lib/python3.6/site-packages/ntlm_auth/compute_response.py", line 206, in _get_LMv2_response
    nt_hash = comphash._ntowfv2(user_name, password, domain_name)
  File "<project-path>/env/lib/python3.6/site-packages/ntlm_auth/compute_hash.py", line 87, in _ntowfv2
    digest = _ntowfv1(password)
  File "<project-path>/env/lib/python3.6/site-packages/ntlm_auth/compute_hash.py", line 67, in _ntowfv1
    if re.match(r'^[a-fA-F\d]{32}:[a-fA-F\d]{32}$', password):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object`

**Comment by Lukasa** [comment]
This looks like your password is a byte string: it needs to be a Unicode or native string. Change that and you should be golden.
