### ISSUE TITLE
ImportError: No module named 'requests.packages'

### ISSUE THREAD

**Issue by WillBishop** [requests/requests-ntlm#99]
On a fresh install of Ubuntu 14.04, requests_ntlm isn't working.

```
root@ubuntu:~/Scripts# python3 monitorReports.py 
Traceback (most recent call last):
  File "monitorReports.py", line 2, in <module>
    from requests_ntlm import HttpNtlmAuth
  File "/usr/local/lib/python3.4/dist-packages/requests_ntlm/__init__.py", line 1, in <module>
    from .requests_ntlm import HttpNtlmAuth
  File "/usr/local/lib/python3.4/dist-packages/requests_ntlm/requests_ntlm.py", line 7, in <module>
    from requests.packages.urllib3.response import HTTPResponse
ImportError: No module named 'requests.packages'
root@ubuntu:~/Scripts# sudo pip3 install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages
```

`import requests` works fine.

Any ideas?

**Comment by WillBishop** [comment]
`pip3 install requests --upgrade` fixed this issue
